feat: preselected destination wallet
sygmaprotocol/sygma-widget pull request #125
Opened 2024-02-29 16:11 UTC by Lykhoyda

The logic will work only for EVM networks as substrate-based networks will have different prefixes.

Closes #102

2024-03-04 22:25 UTC, wainola commented
@mpetrunic will this PR make [this other](https://github.com/sygmaprotocol/sygma-widget/pull/128) PR irrelevant? Since whenever we change the network we are cleaning for diff type and appending for same type 🤔

2024-03-04 22:28 UTC, wainola requested changes

2024-03-04 22:28 UTC, wainola commented on packages/widget/src/components/transfer/fungible/fungible-token-transfer.ts
> +  private isSourceAndDestinationNetworkHasEqualType(): boolean {
```suggestion
  private sourceAndDestinationNetworkHasEqualType(): boolean {
```

2024-03-04 22:33 UTC, wainola commented
@Lykhoyda there is a small issue. If you connect wallet, select diff type of network on dest network and paste a valid substrate address, validation is going to complain saying that is a invalid ethereum address 🙈

2024-03-05 14:42 UTC, Lykhoyda commented
> The logic will work only for EVM networks as substrate-based networks will have different prefixes.
> 
> Closes #102

@wainola yeah, it's true. I created a new PR that I will merge to the main and synced with your previous solution https://github.com/sygmaprotocol/sygma-widget/pull/128

2024-03-05 14:42 UTC, closed without merging