fix: evm amount is now calculated as user input minus the fee
sygmaprotocol/sygma-widget pull request #143
Opened 2024-03-13 12:29 UTC by mpetrunic

## Description

## Related Issue Or Context

Closes: #139 

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-03-13 21:29 UTC, wainola requested changes

2024-03-14 22:55 UTC, wainola submitted a review, later dismissed

2024-03-19 11:10 UTC, mpetrunic commented
Depends on: https://github.com/sygmaprotocol/sygma-sdk/pull/360

2024-03-25 06:56 UTC, mpetrunic commented
This is blocked until, testnet fee handlers are deployed to use latest smart contracts

2024-03-28 14:40 UTC, mpetrunic commented
depends on https://github.com/sygmaprotocol/sygma-sdk/pull/365

2024-03-28 15:07 UTC, Lykhoyda commented on packages/widget/src/controllers/transfers/evm/build.ts
> +  transfer.details;
it's probably not reqired

2024-03-28 15:08 UTC, Lykhoyda submitted a review, later dismissed
Looks good!

2024-04-03 13:38 UTC, wainola approved these changes

2024-04-04 08:52 UTC, MakMuftic approved these changes

2024-04-04 12:39 UTC, merged