fix: Gas Fee estimation behavior, is not consistent for the actual transfer TX
sygmaprotocol/sygma-widget pull request #204
Opened 2024-05-29 10:14 UTC by saadjhk

## Description

Gas estimation for transfer transaction was not calculated as the estimate gas function was called when the transfer state returned from `getTransferState` was the one which had no case handled in `estimateEvmGas`

## Related Issue Or Context

#190 

Closes: #190 

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)

2024-05-29 11:50 UTC, wainola requested changes

2024-05-29 11:50 UTC, wainola commented on packages/widget/src/controllers/transfers/evm/execute.ts
> +      this.estimateGas();
```suggestion
      await this.estimateGas();
```

2024-05-30 10:22 UTC, wainola approved these changes

2024-06-03 13:42 UTC, Lykhoyda approved these changes

2024-06-03 13:46 UTC, merged