feat: base layout for widget
sygmaprotocol/sygma-widget pull request #48
Opened 2023-12-14 03:28 UTC by wainola

## Description

This PR implements base layout and styles for Widget

## Related Issue Or Context

Closes: #7 

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in sygma-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-01-15 15:48 UTC, FSM1 requested changes

2024-01-15 15:48 UTC, FSM1 commented on packages/widget/src/components/widget-app/widget-app.ts
> +        <form @submit=${this.handleTransfer}>
Don't think we need to use a form element here

2024-01-15 15:48 UTC, FSM1 commented on packages/widget/src/components/widget-app/widget-app.ts
> +                html`<button type="submit" class="actionButtonReady">
`type="submit"` forces the page to refresh when the button is pushed. Should rather use `type="button"` and handle the form submission in the `onClick` handler.

2024-01-18 14:29 UTC, mpetrunic approved these changes

2024-01-18 14:29 UTC, merged