feat: add cf deployment
sygmaprotocol/sygma-widget pull request #59
Opened 2024-01-18 16:48 UTC by Lykhoyda

## Description
- Add widget package deployment during the push to the main and when opening a new PR
- Separate deployment of the widget package when a new version is released

Closes: #28

2024-01-19 04:10 UTC, wainola commented
@Lykhoyda how do we envision to deploy the react package?

2024-01-19 12:53 UTC, mpetrunic requested changes
We don't need prod deployment (we are building library here), we just need deploy previews.
It's probably best to rebase against #58

2024-01-19 13:25 UTC, Lykhoyda commented on packages/react/package.json
> +    "@lit-labs/react": "2.1.2"
The changes done to trigger the react workflow

2024-01-19 13:28 UTC, Lykhoyda commented
> @Lykhoyda how do we envision to deploy the react package? I have this question after reading the deploy files for the react package

@wainola the deployment will serve the static file like index.html. The react project is empty for now, so it's just a preparation of the code for future code deployments.

2024-01-19 16:08 UTC, wainola approved these changes

2024-01-19 16:16 UTC, wainola approved these changes

2024-01-22 08:44 UTC, mpetrunic approved these changes

2024-01-22 08:44 UTC, merged